-- Script SAE par PERES Thomas ET PERONI Dylan

-- Creation des tables
CREATE TABLE Utilisateurs (
    utilisateurID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    pseudo VARCHAR2(50) DEFAULT USER NOT NULL UNIQUE, 
    email VARCHAR2(50) NOT NULL UNIQUE,  
    date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    telephone VARCHAR2(20), 
    avatar_url VARCHAR2(255), 
    statut VARCHAR2(20) DEFAULT 'actif', 
    pays VARCHAR2(50) NOT NULL, 
    nb_abonné NUMBER DEFAULT 0 NOT NULL, 
    nb_follower NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT chk_statut CHECK (statut IN ('actif', 'suspendu', 'supprimé')) 
);

CREATE TABLE Categories(
    categorieID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nom_categorie VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Videos (
    videoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR2(255) NOT NULL,
    description CLOB,
    url_video VARCHAR2(255) NOT NULL UNIQUE,
    date_publication TIMESTAMP,
    utilisateurID NUMBER NOT NULL,
    categorieID NUMBER,
    monetisation NUMBER(1) DEFAULT 0,
    vues NUMBER DEFAULT 0,
    visibilite VARCHAR2(20) DEFAULT 'publique',
    CONSTRAINT chk_visibilite_Videos CHECK (visibilite IN ('publique', 'privée')),
    CONSTRAINT fk_utilisateurID_Videos FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_categorieID_Videos FOREIGN KEY (categorieID) REFERENCES Categories(categorieID) ON DELETE SET NULL
);

CREATE TABLE Lives (
    liveID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR2(255) NOT NULL,
    description CLOB,
    url_live VARCHAR2(255) NOT NULL UNIQUE,
    date_debut TIMESTAMP NOT NULL,
    date_fin TIMESTAMP,
    utilisateurID NUMBER NOT NULL,
    categorieID NUMBER,
    statut VARCHAR2(20) DEFAULT 'programme' NOT NULL,
    CONSTRAINT chk_statut_live CHECK (statut IN ('encours', 'termine', 'programme')),
    CONSTRAINT fk_utilisateurID_Lives FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_categorieID_Lives FOREIGN KEY (categorieID) REFERENCES Categories(categorieID) ON DELETE SET NULL
);

CREATE TABLE Tags (
    tagID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_tag VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE VideosTags (
    videoID NUMBER NOT NULL,
    tagID NUMBER NOT NULL,
    PRIMARY KEY (videoID, tagID),
    CONSTRAINT fk_videoID_VideoTag FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE,
    CONSTRAINT fk_tagID_VideoTag FOREIGN KEY (tagID) REFERENCES Tags(tagID) ON DELETE CASCADE
);


CREATE TABLE LivesTags (
    liveID NUMBER NOT NULL,
    tagID NUMBER NOT NULL,
    PRIMARY KEY (liveID, tagID),
    CONSTRAINT fk_liveID_LiveTag FOREIGN KEY (liveID) REFERENCES Lives(liveID) ON DELETE CASCADE,
    CONSTRAINT fk_tagID_LiveTag FOREIGN KEY (tagID) REFERENCES Tags(tagID) ON DELETE CASCADE
);

CREATE TABLE CommentairesVideos (
    commentaireID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentaire_parentID NUMBER,
    contenu VARCHAR2(255),
    date_commentaire TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    utilisateurID NUMBER NOT NULL,
    videoID NUMBER NOT NULL,
    CONSTRAINT fk_commentaire_video_parentID FOREIGN KEY (commentaire_parentID) REFERENCES CommentairesVideos(commentaireID) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateurID_commentaireVideo FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID_commentaire FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE
);

CREATE TABLE CommentairesLives (
    commentaireID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentaire_parentID NUMBER,
    contenu VARCHAR2(255),
    date_commentaire TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    utilisateurID NUMBER NOT NULL,
    liveID NUMBER NOT NULL,
    CONSTRAINT fk_commentaire_live_parentID FOREIGN KEY (commentaire_parentID) REFERENCES CommentairesLives(commentaireID) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateurID_commentaireLive FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_liveID_commentaire FOREIGN KEY (liveID) REFERENCES Lives(liveID) ON DELETE CASCADE
);

CREATE TABLE Abonnements (
    abonnementID NUMBER NOT NULL,
    abonneID NUMBER NOT NULL,
    date_abonnement TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR2(20) DEFAULT 'actif',
    CONSTRAINT pk_abonnement PRIMARY KEY (abonnementID, abonneID),
    CONSTRAINT chk_statut_Abonnement CHECK (statut IN ('actif', 'expiré')),
    CONSTRAINT fk_abonnementID FOREIGN KEY (abonnementID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_abonneID FOREIGN KEY (abonneID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Follow (
    followID NUMBER NOT NULL,
    followerID NUMBER NOT NULL,
    date_follow TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_follow PRIMARY KEY (followID, followerID),
    CONSTRAINT fk_followID FOREIGN KEY (followID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_followerID FOREIGN KEY (followerID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Interactions (
    interactionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_interaction VARCHAR2(20) NOT NULL,
    utilisateurID NUMBER NOT NULL,
    videoID NUMBER,
    commentaireID NUMBER,
    date_interaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_type_interaction CHECK (type_interaction IN ('like', 'dislike')),
    CONSTRAINT fk_utilisateurID_Interactions FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID_Interactions FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE,
    CONSTRAINT fk_commentaireID_Interactions FOREIGN KEY (commentaireID) REFERENCES CommentairesVideos(commentaireID) ON DELETE CASCADE,
    CONSTRAINT chk_interaction CHECK (
        (videoID IS NOT NULL AND commentaireID IS NULL) OR 
        (commentaireID IS NOT NULL AND videoID IS NULL)
    )
);

CREATE TABLE Historique (
    historiqueID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    videoID NUMBER NOT NULL,
    date_visionnage TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilisateurID_Historique FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID_Historique FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE
);

CREATE TABLE Playlists (
    playlistID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR2(255) NOT NULL,
    description CLOB,
    utilisateurID NUMBER NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    visibilite VARCHAR2(20) DEFAULT 'publique',
    CONSTRAINT chk_visibilite_Playlists CHECK (visibilite IN ('publique', 'privée', 'non répertoriée')),
    CONSTRAINT fk_utilisateurID_Playlists FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE PlaylistsVideos (
    playlistID NUMBER NOT NULL,
    videoID NUMBER NOT NULL,
    ordre NUMBER NOT NULL,
    PRIMARY KEY (playlistID, videoID),
    CONSTRAINT fk_playlistID_PlaylistsVideos FOREIGN KEY (playlistID) REFERENCES Playlists(playlistID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID_PlaylistsVideos FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE
);

CREATE TABLE Revenus (
    revenuID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    montant_total DECIMAL(10, 2) NOT NULL,
    dernière_maj TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilisateurID_Revenus FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Moderateur (
    moderateurID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_nomination TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_moderateurID FOREIGN KEY (moderateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Signalements (
    signalementID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo_signaleur VARCHAR2(100) NOT NULL,
    utilisateur_cibleID NUMBER,
    videoID NUMBER,
    liveID NUMBER,
    commentaire_videoID NUMBER,
    commentaire_liveID NUMBER,
    raison CLOB NOT NULL,
    date_signalement TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR2(20) DEFAULT 'en attente' NOT NULL,
    moderateurID NUMBER,
    CONSTRAINT chk_statut_signalement CHECK (statut IN ('enattente', 'traite', 'rejete')),
    CONSTRAINT fk_pseudo_signaleur FOREIGN KEY (pseudo_signaleur) REFERENCES Utilisateurs(pseudo) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateur_cibleID FOREIGN KEY (utilisateur_cibleID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE,
    CONSTRAINT fk_liveID FOREIGN KEY (liveID) REFERENCES Lives(liveID) ON DELETE CASCADE,
    CONSTRAINT fk_commentaire_videoID FOREIGN KEY (commentaire_videoID) REFERENCES CommentairesVideos(commentaireID) ON DELETE CASCADE,
    CONSTRAINT fk_commentaire_liveID FOREIGN KEY (commentaire_liveID) REFERENCES CommentairesLives(commentaireID) ON DELETE CASCADE,
    CONSTRAINT fk_moderateurID_Signalement FOREIGN KEY (moderateurID) REFERENCES Moderateur(moderateurID) ON DELETE SET NULL,
    CONSTRAINT chk_signalement CHECK (
        (utilisateur_cibleID IS NOT NULL AND videoID IS NULL AND commentaire_videoID IS NULL AND liveID IS NULL AND commentaire_liveID IS NULL) OR 
        (videoID IS NOT NULL AND utilisateur_cibleID IS NULL AND commentaire_videoID IS NULL AND liveID IS NULL AND commentaire_liveID IS NULL) OR  
        (liveID IS NOT NULL AND utilisateur_cibleID IS NULL AND commentaire_videoID IS NULL AND videoID IS NULL AND commentaire_liveID IS NULL) OR
        (commentaire_videoID IS NOT NULL AND utilisateur_cibleID IS NULL AND videoID IS NULL AND liveID IS NULL AND commentaire_liveID IS NULL) OR
	(commentaire_liveID IS NOT NULL AND utilisateur_cibleID IS NULL AND videoID IS NULL AND liveID IS NULL AND commentaire_videoID IS NULL)
    )
);

CREATE TABLE Notifications (
    notificationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    contenu CLOB NOT NULL,
    lu CHAR(1) DEFAULT 'F',
    date_notif TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type_notification VARCHAR2(20) DEFAULT 'autre',
    CONSTRAINT chk_type_notification CHECK (type_notification IN ('nouvel_abonne', 'nouveau_commentaire', 'alerte', 'autre')),
    CONSTRAINT fk_utilisateurID_Notifications FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Preniums (
    abonnementID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    date_debut TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_fin TIMESTAMP NOT NULL,
    montant DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_utilisateurID_Prenium FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Annonceurs (
    annonceurID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    telephone VARCHAR2(20)
);

CREATE TABLE Annonces (
    annonceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annonceurID NUMBER NOT NULL,
    type_annonce VARCHAR2(20) CHECK (type_annonce IN ('video', 'banniere')) NOT NULL,
    url_media VARCHAR2(255) NOT NULL,
    titre VARCHAR2(255),
    description CLOB,
    duree_sec NUMBER,
    CONSTRAINT fk_annonceurID FOREIGN KEY (annonceurID) REFERENCES Annonceurs(annonceurID) ON DELETE CASCADE
);

CREATE TABLE DiffusionsPubs (
    diffusionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annonceID NUMBER NOT NULL,
    videoID NUMBER,
    liveID NUMBER,
    utilisateurID NUMBER,
    date_diffusion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type_interaction VARCHAR2(10) DEFAULT 'vue' CHECK (type_interaction IN ('vue', 'clic')),
    CONSTRAINT fk_annonceID_Diff FOREIGN KEY (annonceID) REFERENCES Annonces(annonceID) ON DELETE CASCADE,
    CONSTRAINT fk_videoID_Diff FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE SET NULL,
    CONSTRAINT fk_liveID_Diff FOREIGN KEY (liveID) REFERENCES Lives(liveID) ON DELETE SET NULL,
    CONSTRAINT fk_utilisateurID_Diff FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE SET NULL,
    CONSTRAINT chk_diffusion CHECK (
        (videoID IS NOT NULL AND liveID IS NULL) OR
	(liveID IS NOT NULL AND videoID IS NULL)
    )
);

CREATE TABLE PaiementsPub (
    paiementID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annonceurID NUMBER NOT NULL,
    utilisateurID NUMBER NOT NULL,
    montant DECIMAL(10, 2) NOT NULL,
    date_paiement TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_annonceurID_PaiementsPub FOREIGN KEY (annonceurID) REFERENCES Annonceurs(annonceurID) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateurID_PaiementsPub FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Dons (
    donID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_donneurID NUMBER,
    liveID NUMBER NOT NULL,
    montant DECIMAL(10, 2) NOT NULL,
    message CLOB,
    date_don TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_donneur FOREIGN KEY (utilisateur_donneurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE SET NULL,
    CONSTRAINT fk_liveID_Dons FOREIGN KEY (liveID) REFERENCES Lives(liveID) ON DELETE CASCADE
);

CREATE TABLE Recherches (
    rechercheID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    contenu CLOB NOT NULL,
    date_recherche TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NB_resultats NUMBER DEFAULT 0,
    CONSTRAINT fk_utilisateur_recherche FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);

CREATE TABLE Recommendations (
    recommendation_videoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateurID NUMBER NOT NULL,
    videoID NUMBER NOT NULL,
    type_suggestion VARCHAR2(20) CHECK (type_suggestion IN ('historique', 'populaire', 'tendance', 'similaire')) NOT NULL,
    date_suggestion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilisateur_recommendation FOREIGN KEY (utilisateurID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_video_recommendation FOREIGN KEY (videoID) REFERENCES Videos(videoID) ON DELETE CASCADE
);

CREATE TABLE HistoriqueRecherche (
    historique_rechercheID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rechercheID NUMBER NOT NULL,
    CONSTRAINT fk_recherche_historique FOREIGN KEY (rechercheID) REFERENCES Recherches(rechercheID) ON DELETE CASCADE
);

CREATE TABLE BloquageUtilisateurs (
    utilisateur_bloqueur_ID NUMBER NOT NULL,
    utilisateur_bloque_ID NUMBER NOT NULL,
    date_bloquage TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bloquage PRIMARY KEY (utilisateur_bloqueur_ID, utilisateur_bloque_ID),
    CONSTRAINT fk_bloqueur FOREIGN KEY (utilisateur_bloqueur_ID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE,
    CONSTRAINT fk_bloque FOREIGN KEY (utilisateur_bloque_ID) REFERENCES Utilisateurs(utilisateurID) ON DELETE CASCADE
);


-- Création des vues

-- Vue d'un utilisateurs sur les autres utilisateurs
CREATE VIEW VueUtilisateurs_AutresUtilisateurs AS
SELECT pseudo, nb_abonné, date_inscription, statut
FROM Utilisateurs
WHERE pseudo != USER;

-- Vue d'un utilisateurs sur lui même 
CREATE VIEW VueUtilisateurs_Utilisateur AS
SELECT u.utilisateurID, pseudo, email, date_inscription, telephone, avatar_url, u.statut AS Statut_du_Compte, pays, nb_abonné, nb_follower, r.montant_total AS revenue, p.date_fin AS expiration_prenium
FROM Utilisateurs u, Revenus r, Preniums p
WHERE u.utilisateurID = r.utilisateurID AND u.utilisateurID = p.utilisateurID AND pseudo = USER;

-- Vue des utilisateurs sur les autres vidéos publiques
CREATE VIEW VueVideos_VideosPubliquesAutresUtilisateurs AS
SELECT v.titre, v.description, v.url_video, v.date_publication, v.vues, c.nom_categorie, u.pseudo, t.nom_tag
FROM Utilisateurs u, Videos v, VideosTags vt, Tags t, Categories c
WHERE u.utilisateurID = v.utilisateurID AND v.videoID = vt.videoID AND t.tagID = vt.tagID AND v.categorieID = c.categorieID AND v.visibilite = 'publique' AND u.pseudo != USER;

-- Vue des utilisateurs sur leurs vidéos publiques
CREATE VIEW VueVideos_VideosPubliques AS
SELECT v.titre, v.description, v.url_video, v.date_publication, v.vues, c.nom_categorie, v.monetisation, u.pseudo, t.nom_tag
FROM Utilisateurs u, Videos v, VideosTags vt, Tags t, Categories c
WHERE u.utilisateurID = v.utilisateurID AND v.videoID = vt.videoID AND t.tagID = vt.tagID AND v.categorieID = c.categorieID AND v.visibilite = 'publique' AND u.pseudo = USER;

-- Vue des utilisateurs sur leurs vidéos privées
CREATE VIEW VueVideos_VideosPrivée AS
SELECT v.titre, v.description, v.url_video, v.date_publication, v.vues, c.nom_categorie, v.monetisation, u.pseudo, t.nom_tag
FROM Utilisateurs u, Videos v, VideosTags vt, Tags t, Categories c
WHERE u.utilisateurID = v.utilisateurID AND v.videoID = vt.videoID AND t.tagID = vt.tagID AND v.categorieID = c.categorieID AND v.visibilite = 'privée' AND u.pseudo = USER;

-- Vue des utilisateurs sur les lives
CREATE VIEW VueLives AS
SELECT l.titre, l.description, l.url_live, l.date_debut, c.nom_categorie, u.pseudo, t.nom_tag
FROM Utilisateurs u, Lives l, LivesTags lt, Tags t, Categories c
WHERE u.utilisateurID = l.utilisateurID AND l.liveID = lt.liveID AND t.tagID = lt.tagID AND l.categorieID = c.categorieID AND u.pseudo != USER;

-- Vue des utilisateurs sur les commentaires des vidéos publiques
CREATE VIEW VueCommentairesVideos_VideosPubliques AS
SELECT v.titre, v.url_video, v.date_publication, c.contenu, c.date_commentaire, u.pseudo
FROM Utilisateurs u, CommentairesVideos c, Videos v
WHERE u.utilisateurID = c.utilisateurID AND c.videoID = v.videoID AND v.visibilite = 'publique'
ORDER BY c.date_commentaire DESC;

-- Vue des utilisateurs sur les commentaires des lives
CREATE VIEW VueCommentairesLives_Lives AS
SELECT l.titre, l.url_live, l.date_debut, c.contenu, c.date_commentaire, u.pseudo
FROM Utilisateurs u, CommentairesLives c, Lives l
WHERE u.utilisateurID = c.utilisateurID AND c.liveID = l.liveID
ORDER BY c.date_commentaire DESC;

-- Vue des utilisateurs sur les pubs des vidéos publiques
CREATE VIEW VueDiffusionsPubs_Videos AS
SELECT v.titre AS titre_video, v.url_video, a.titre AS titre_annonce, a.url_media, a.type_annonce, d.date_diffusion, d.type_interaction,u.pseudo
FROM Utilisateurs u, Annonces a, Videos v, DiffusionsPubs d
WHERE u.utilisateurID = d.utilisateurID AND d.annonceID = a.annonceID AND d.videoID = v.videoID AND v.visibilite = 'publique';

-- Vue des utilisateurs sur les pubs des lives
CREATE VIEW VueDiffusionsPubs_Lives AS
SELECT l.titre AS titre_live, l.url_live, a.titre AS titre_annonce, a.url_media, a.type_annonce, d.date_diffusion, d.type_interaction, u.pseudo
FROM Utilisateurs u, Annonces a, Lives l, DiffusionsPubs d
WHERE u.utilisateurID = d.utilisateurID AND d.annonceID = a.annonceID AND d.liveID = l.liveID;

-- Vue des utilisateurs sur leurs playlists privées
CREATE VIEW VuePlaylistsVideosPrivees AS
SELECT p.titre, p.description, p.visibilite, p.date_creation, u.pseudo
FROM Playlists p, Utilisateurs u
WHERE p.utilisateurID = u.utilisateurID AND p.visibilite = 'privée' AND u.pseudo = USER
ORDER BY p.date_creation DESC;

-- Vue des utilisateurs sur les playlists publiques
CREATE VIEW VuePlaylisPubliques AS
SELECT p.titre, p.description, p.visibilite, p.date_creation, u.pseudo
FROM Playlists p, Utilisateurs u
WHERE p.utilisateurID = u.utilisateurID AND p.visibilite = 'publique'
ORDER BY p.date_creation DESC;

-- Vue des utilisateurs sur leur historique de recherche
CREATE VIEW VueHistoriquesRecherches_Utilisateur AS
SELECT r.contenu, r.date_recherche, r.NB_resultats
FROM HistoriqueRecherche hr, Recherches r, Utilisateurs u
WHERE hr.rechercheID = r.rechercheID AND r.utilisateurID = u.utilisateurID AND u.pseudo = USER
ORDER BY r.date_recherche DESC;

-- Vue des utilisateurs sur leur historique de vidéos visionnées
CREATE VIEW VueHistoriquesVideos_Utilisateur AS
SELECT v.titre, h.date_visionnage
FROM Historique h, Videos v, Utilisateurs u
WHERE h.utilisateurID = u.utilisateurID AND h.videoID = v.videoID AND u.pseudo = USER
ORDER BY h.date_visionnage DESC;

-- Vue des moderateurs sur les utilisateurs
CREATE VIEW VueModos_Utilisateurs AS
SELECT utilisateurID, pseudo, email, telephone, statut, pays, nb_abonné, nb_follower, date_inscription
FROM Utilisateurs;

-- Vue des utilisateurs sur les interactions d'une vidéo publique
CREATE VIEW VueInteractions_VideosPubliques AS
SELECT v.titre, v.url_video, v.date_publication, v.vues,
       COUNT(CASE WHEN i.type_interaction = 'like' THEN 1 END) AS nb_likes,
       COUNT(CASE WHEN i.type_interaction = 'dislike' THEN 1 END) AS nb_dislikes,
       COUNT(c.commentaireID) AS nb_commentaires
FROM Videos v, Interactions i, CommentairesVideos c
WHERE v.videoID = i.videoID AND v.videoID = c.videoID AND v.visibilite = 'publique'
GROUP BY v.videoID, v.titre, v.url_video, v.date_publication, v.vues;

-- Vue des utilisateurs sur les interactions d'une vidéo privée
CREATE VIEW VueInteractions_VideosPrivees AS
SELECT v.titre, v.url_video, v.date_publication, v.vues,
       COUNT(CASE WHEN i.type_interaction = 'like' THEN 1 END) AS nb_likes,
       COUNT(CASE WHEN i.type_interaction = 'dislike' THEN 1 END) AS nb_dislikes
FROM Videos v, Interactions i, Utilisateurs u
WHERE v.videoID = i.videoID AND v.visibilite = 'privée' AND u.pseudo = USER
GROUP BY v.videoID, v.titre, v.url_video, v.date_publication, v.vues;

-- Vue des utilisateurs sur les interactions d'un commentaire vidéo
CREATE VIEW VueInteractions_Commentaires AS
SELECT v.titre, v.url_video, v.date_publication, c.contenu,
       COUNT(CASE WHEN i.type_interaction = 'like' THEN 1 END) AS nb_likes,
       COUNT(CASE WHEN i.type_interaction = 'dislike' THEN 1 END) AS nb_dislikes
FROM Videos v, CommentairesVideos c, Interactions i
WHERE v.videoID = c.videoID AND c.commentaireID = i.commentaireID AND v.visibilite = 'publique'
GROUP BY c.commentaireID, v.titre, v.url_video, v.date_publication, c.contenu;

-- Vue des moderateurs sur les videos
CREATE VIEW VueModo_Videos AS
SELECT u.pseudo, v.titre, v.description, v.url_video, v.date_publication, c.nom_categorie, v.monetisation, v.vues, v.visibilite 
FROM Videos v, Utilisateurs u, Categories c
WHERE u.utilisateurID = v.utilisateurID AND v.categorieID = c.categorieID AND v.visibilite = 'publique';

-- Vue des modérateurs sur les signalements d'une chaine/d'un utilisateur
CREATE VIEW VueModo_Signalement_Chaine AS
SELECT u.pseudo AS Personne_Signalée, s.raison, s.date_signalement, s.statut, s.pseudo_signaleur AS Signaleur
FROM Signalements s, Utilisateurs u
WHERE s.utilisateur_cibleID IS NOT NULL and s.utilisateur_cibleID = u.utilisateurID;

-- Vue des modérateurs sur les signalements d'une video
CREATE VIEW VueModo_Signalement_Videos AS
SELECT v.url_video, v.titre, s.raison, s.date_signalement, s.statut, s.pseudo_signaleur AS Signaleur
FROM Signalements s, Utilisateurs u, Videos v
WHERE s.videoID IS NOT NULL AND s.videoID = v.videoID ;

-- Vue des modérateurs sur les signalements d'un live
CREATE VIEW VueModo_Signalement_Lives AS
SELECT l.url_live, l.titre, s.raison, s.date_signalement, s.statut, s.pseudo_signaleur AS Signaleur
FROM Signalements s, Utilisateurs u, Lives l
WHERE s.liveID IS NOT NULL AND s.liveID = l.liveID;

-- Vue des modérateurs sur les signalements de commentaire sur une vidéo
CREATE VIEW VueModo_Signalement_CommentairesVideos AS
SELECT c.commentaireID, c.contenu, s.raison, s.date_signalement, s.statut, s.pseudo_signaleur AS Signaleur
FROM Signalements s, Utilisateurs u, CommentairesVideos c
WHERE s.commentaire_videoID IS NOT NULL AND s.commentaire_videoID = c.commentaireID;

-- Vue des modérateurs sur les signalements de commentaire sur un live
CREATE VIEW VueModo_Signalement_CommentairesLives AS
SELECT c.commentaireID, c.contenu, s.raison, s.date_signalement, s.statut, s.pseudo_signaleur AS Signaleur
FROM Signalements s, Utilisateurs u, CommentairesLives c
WHERE s.commentaire_liveID IS NOT NULL AND s.commentaire_liveID = c.commentaireID;

-- Vue des notifications d'un utilisateur
CREATE VIEW VueNotification_Utilisateur AS
SELECT n.date_notif, n.contenu, n.type_notification
FROM Notifications n, Utilisateurs u
WHERE n.utilisateurID = u.utilisateurID AND u.pseudo = USER;

-- Vue des videos des playlists de l'utilisateur
CREATE VIEW Vue_PlaylistVideo_Utilisateur AS
SELECT  pv.ordre, v.titre AS Titre_Video
FROM Utilisateurs u, Playlists p, PlaylistsVideos pv, Videos v
WHERE u.utilisateurID = p.utilisateurID AND u.pseudo = USER AND p.playlistID = pv.playlistID AND v.videoID = pv.videoID
ORDER BY pv.ordre ASC;

-- Vue des utilisateurs bloqués par l'utilisateur
CREATE View Vue_Utilisateur_Bloquer AS
SELECT T.pseudo, b.date_bloquage
FROM Utilisateurs u, BloquageUtilisateurs b, (SELECT pseudo, utilisateurID FROM Utilisateurs) T
WHERE u.pseudo = USER AND u.utilisateurID = b.utilisateur_bloqueur_ID AND T.utilisateurID = b.utilisateur_bloque_ID;

-- Vue des recommendations faite a un utilisateur
CREATE View Vue_Recommendation AS
SELECT v.titre, r.date_suggestion, r.type_suggestion
FROM Recommendations r, Utilisateurs u, Videos v
WHERE r.utilisateurID = u.utilisateurID AND pseudo = USER AND v.videoID = r.videoID;


-- Creation du role Moderateur
CREATE ROLE MODERATEUR;

-- Attribution des droits

-- Select
GRANT SELECT ON VueUtilisateurs_AutresUtilisateurs TO PUBLIC;
GRANT SELECT ON VueVideos_VideosPubliquesAutresUtilisateurs TO PUBLIC;
GRANT SELECT ON VueVideos_VideosPubliques TO PUBLIC;
GRANT SELECT ON VueVideos_VideosPrivée TO PUBLIC;
GRANT SELECT ON VueLives TO PUBLIC;
GRANT SELECT ON VueCommentairesVideos_VideosPubliques TO PUBLIC;
GRANT SELECT ON VueCommentairesLives_Lives TO PUBLIC;
GRANT SELECT ON VueDiffusionsPubs_Videos TO PUBLIC;
GRANT SELECT ON VueDiffusionsPubs_Lives TO PUBLIC;
GRANT SELECT ON VuePlaylistsVideosPrivees TO PUBLIC;
GRANT SELECT ON VuePlaylisPubliques TO PUBLIC;
GRANT SELECT ON VueHistoriquesRecherches_Utilisateur TO PUBLIC;
GRANT SELECT ON VueHistoriquesVideos_Utilisateur TO PUBLIC;
GRANT SELECT ON VueInteractions_VideosPubliques TO PUBLIC;
GRANT SELECT ON VueInteractions_VideosPrivees TO PUBLIC;
GRANT SELECT ON VueInteractions_Commentaires TO PUBLIC;
GRANT SELECT ON VueInteractions_Commentaires TO PUBLIC;
GRANT SELECT ON VueNotification_Utilisateur TO PUBLIC;
GRANT SELECT ON Vue_PlaylistVideo_Utilisateur TO PUBLIC;
GRANT SELECT ON Vue_Utilisateur_Bloquer TO PUBLIC;
GRANT SELECT ON Vue_Recommendation TO PUBLIC;

GRANT SELECT ON VueModos_Utilisateurs TO MODERATEUR;
GRANT SELECT ON VueModo_Videos TO MODERATEUR;
GRANT SELECT ON VueModo_Signalement_Chaine TO MODERATEUR;
GRANT SELECT ON VueModo_Signalement_Videos TO MODERATEUR;
GRANT SELECT ON VueModo_Signalement_Lives TO MODERATEUR;
GRANT SELECT ON VueModo_Signalement_CommentairesVideos TO MODERATEUR;
GRANT SELECT ON VueModo_Signalement_CommentairesLives TO MODERATEUR;

-- Insert
GRANT INSERT (titre,description,url_video,visibilite) ON Videos TO PUBLIC;
GRANT INSERT (titre,description,url_live,date_debut,date_fin) ON Lives TO PUBLIC;

-- Update
GRANT UPDATE (statut) ON VueModo_Signalement_Chaine TO MODERATEUR;
GRANT UPDATE (statut) ON VueModo_Signalement_Videos TO MODERATEUR;
GRANT UPDATE (statut) ON VueModo_Signalement_Lives TO MODERATEUR;
GRANT UPDATE (statut) ON VueModo_Signalement_CommentairesVideos TO MODERATEUR;
GRANT UPDATE (statut) ON VueModo_Signalement_CommentairesLives TO MODERATEUR;
GRANT UPDATE (statut) ON Utilisateurs TO MODERATEUR;


-- Creation des triggers

-- Trigger pour mettre a jour le montant du revenus après d'une insertion sur la table Dons
CREATE OR REPLACE TRIGGER MAJ_Revenus_Dons
AFTER INSERT ON Dons
FOR EACH ROW
BEGIN
    -- Mise à jour des revenus avec le montant du don
    UPDATE Revenus
    SET montant_total = montant_total + :NEW.montant
    WHERE utilisateurID = (SELECT utilisateurID FROM Lives WHERE liveID = :NEW.liveID);
    -- Mise a jour de la date
    UPDATE Revenus
    SET dernière_maj = CURRENT_TIMESTAMP
    WHERE utilisateurID = (SELECT utilisateurID FROM Lives WHERE liveID = :NEW.liveID);
END;
/

-- Trigger pour mettre a jour le montant du revenus après d'une insertion sur la table Videos (monetisation)
CREATE OR REPLACE TRIGGER MAJ_Revenus_Videos
AFTER INSERT ON Videos
FOR EACH ROW
BEGIN
    -- Mise à jour des revenus avec le montant de la rémuneration
    UPDATE Revenus
    SET montant_total = montant_total + :NEW.monetisation
    WHERE utilisateurID = :NEW.utilisateurID;
    -- Mise a jour de la date
    UPDATE Revenus
    SET dernière_maj = CURRENT_TIMESTAMP
    WHERE utilisateurID = :NEW.utilisateurID;
END;
/

-- Trigger pour mettre a jour le montant du revenus après d'une insertion sur la table PaiementsPub
CREATE OR REPLACE TRIGGER MAJ_Revenus_PaiementPub
AFTER INSERT ON PaiementsPub
FOR EACH ROW
BEGIN
    -- Mise à jour des revenus avec le montant du paiement de la pub
    UPDATE Revenus
    SET montant_total = montant_total + :NEW.montant
    WHERE utilisateurID = :NEW.utilisateurID;
    -- Mise a jour de la date
    UPDATE Revenus
    SET dernière_maj = CURRENT_TIMESTAMP
    WHERE utilisateurID = :NEW.utilisateurID;
END;
/

-- Trigger pour mettre a jour le nomnre d'abonné d'un utilisateur
CREATE OR REPLACE TRIGGER Augmenter_Nb_Abonnes
AFTER INSERT ON Abonnements
FOR EACH ROW
BEGIN
    -- Augmenter le nombre d'abonnés de l'utilisateur
    UPDATE Utilisateurs
    SET nb_abonné = nb_abonné + 1
    WHERE utilisateurID = :NEW.abonnementID;
END;
/

-- Trigger pour mettre a jour le nomnre de follower d'un utilisateur
CREATE OR REPLACE TRIGGER Augmenter_Nb_Follower
AFTER INSERT ON Follow
FOR EACH ROW
BEGIN
    -- Augmenter le nombre de follower de l'utilisateur
    UPDATE Utilisateurs
    SET nb_follower = nb_follower + 1
    WHERE utilisateurID = :NEW.followID;
END;
/

-- Trigger pour mettre a jour le nomnre de vues d'une vidéo
CREATE OR REPLACE TRIGGER Augmenter_Nb_Vues
AFTER INSERT ON Historique
FOR EACH ROW
BEGIN
    -- Augmenter le nombre de vue de la video
    UPDATE Videos
    SET vues = vues + 1
    WHERE Videos.videoID = :NEW.videoID;
END;
/