from PIL import Image
def charger_images(COTE_X, COTE_Y):
    """
    Charge les images du jeu et les redimensionne pour un affichage optimal.
    :param COTE_X:
    :param COTE_Y:
    :return: Les images du jeu redimensionnées
    """
    #
    # Importation des images
    #

    # Charger l'image
    image_mur = Image.open("images/mur.png")
    image_colonne = Image.open("images/colonne.png")
    image_fantome = Image.open("images/fantome.png")
    image_joueur = Image.open("images/joueur.png")
    image_bomb = Image.open("images/bomb.png")
    image_explosion = Image.open("images/explosion.png")
    image_porte = Image.open("images/porte.png")
    image_ethernet = Image.open("images/ethernet.png")
    image_upgrade = Image.open("images/upgrade.png")
    image_victoire = Image.open("images/victoire.png")
    image_gameover = Image.open("images/gameover.png")
    image_rejouer = Image.open("images/rejouer.png")
    image_souris = Image.open("images/souris.png")
    image_clavier = Image.open("images/clavier.png")
    image_quitter = Image.open("images/quitter.png")
    image_vie = Image.open("images/vie.png")
    image_feu = Image.open("images/feu.png")
    image_fantome_2 = Image.open("images/fantome_2.png")
    image_bombe_feu = Image.open("images/bombe_feu.png")
    image_bombe_nucleaire = Image.open("images/bombe_nucleaire.png")
    image_explosion_nucleaire = Image.open("images/explosion_nucleaire.png")
    image_score = Image.open("images/score.png")
    image_retour = Image.open("images/retour.png")
    image_suivant = Image.open("images/suivant.png")
    image_precedent = Image.open("images/precedent.png")
    image_erreur = Image.open("images/erreur.png")
    image_death = Image.open("images/death.png")
    image_gold = Image.open("images/gold.png")
    image_argent = Image.open("images/argent.png")
    image_bronze = Image.open("images/bronze.png")
    image_niveau = Image.open("images/niveau.png")
    image_trophee = Image.open("images/trophee.png")

    # Redimensionner l'image
    nouvelle_taille = (COTE_X, COTE_Y)
    grande_taille = (COTE_X * 5, COTE_Y * 5)
    taille_intermediaire = (COTE_X * 3, COTE_Y * 3)

    mur = image_mur.resize(nouvelle_taille)
    colonne = image_colonne.resize(nouvelle_taille)
    fantome = image_fantome.resize(nouvelle_taille)
    joueur = image_joueur.resize(nouvelle_taille)
    bomb = image_bomb.resize(nouvelle_taille)
    explosion = image_explosion.resize(nouvelle_taille)
    porte = image_porte.resize(nouvelle_taille)
    ethernet = image_ethernet.resize(nouvelle_taille)
    upgrade = image_upgrade.resize(nouvelle_taille)
    victoire = image_victoire.resize(grande_taille)
    gameover = image_gameover.resize(grande_taille)
    rejouer = image_rejouer.resize(taille_intermediaire)
    souris = image_souris.resize(grande_taille)
    clavier = image_clavier.resize(grande_taille)
    quitter = image_quitter.resize(taille_intermediaire)
    vie = image_vie.resize(nouvelle_taille)
    feu = image_feu.resize(nouvelle_taille)
    fantome_2 = image_fantome_2.resize(nouvelle_taille)
    bombe_feu = image_bombe_feu.resize(nouvelle_taille)
    bombe_nucleaire = image_bombe_nucleaire.resize(nouvelle_taille)
    explosion_nucleaire = image_explosion_nucleaire.resize(nouvelle_taille)
    score = image_score.resize(taille_intermediaire)
    retour = image_retour.resize(taille_intermediaire)
    suivant = image_suivant.resize(taille_intermediaire)
    precedent = image_precedent.resize(taille_intermediaire)
    erreur = image_erreur.resize(grande_taille)
    death = image_death.resize(nouvelle_taille)
    gold = image_gold.resize(nouvelle_taille)
    argent = image_argent.resize(nouvelle_taille)
    bronze = image_bronze.resize(nouvelle_taille)
    niveau = image_niveau.resize(nouvelle_taille)
    trophee = image_trophee.resize(taille_intermediaire)


    # Sauvegarder l'image redimensionnée
    mur.save("images/mur.png")
    colonne.save("images/colonne.png")
    fantome.save("images/fantome.png")
    joueur.save("images/joueur.png")
    bomb.save("images/bomb.png")
    explosion.save("images/explosion.png")
    porte.save("images/porte.png")
    ethernet.save("images/ethernet.png")
    upgrade.save("images/upgrade.png")
    victoire.save("images/victoire.png")
    gameover.save("images/gameover.png")
    rejouer.save("images/rejouer.png")
    souris.save("images/souris.png")
    clavier.save("images/clavier.png")
    quitter.save("images/quitter.png")
    vie.save("images/vie.png")
    feu.save("images/feu.png")
    fantome_2.save("images/fantome_2.png")
    bombe_feu.save("images/bombe_feu.png")
    bombe_nucleaire.save("images/bombe_nucleaire.png")
    explosion_nucleaire.save("images/explosion_nucleaire.png")
    score.save("images/score.png")
    retour.save("images/retour.png")
    suivant.save("images/suivant.png")
    precedent.save("images/precedent.png")
    erreur.save("images/erreur.png")
    death.save("images/death.png")
    gold.save("images/gold.png")
    argent.save("images/argent.png")
    bronze.save("images/bronze.png")
    niveau.save("images/niveau.png")
    trophee.save("images/trophee.png")